= Powering the Push to Production: A multi-path, live action adventure!

== Maintainer

* Mark Heckler
* mailto:mark@thehecklers.com[mark@thehecklers.com]
* mailto:mark.heckler@gmail.com[mark.heckler@gmail.com]
* https://twitter.com/mkheck[@mkheck on Twitter/X]

== Purpose

This meta-repo accompanies my session titled *"Powering the Push to Production: A multi-path, live action adventure!"* and includes the code written within the session and much more. Please star+watch to be notified of updates, as there will be _many_.

== Notes

I'll be updating this repo with full instructions for how to reproduce - with as little pain as possible - the various scenarios I show in the accompanying session, along with several others...and permutations of each where applicable. I know I keep saying this, but...

*_Please star+watch this repo for updates!_*

== Related repositories

https://github.com/mkheck/ppp[Setup scripts]

https://github.com/mkheck/ppp-deploy-pg[Original application, deployments using az cli and Terraform (for now)]

https://github.com/mkheck/ppp-deploy-pg17[Application with some experimental changes, including Java 17 and deployments using GitHub Actions (more to be added, changes certain) :)]

== To reproduce the scenarios shown in the presentation

. Clone the component repositories listed above to your local machine.
. Follow the instructions in the setup scripts README to initialize necessary environment variables on your machine. NOTE: These are shell scripts to be used in Linux, Mac, and WSL2 environments. If you're using Windows, you'll need to translate the scripts to PowerShell.
. Follow the instructions in the README of each component repository to deploy the application to your Azure subscription.
. When you're done, you can delete the resources created by the deployment scripts by referring to the README of each component repository.

== Related presentation

https://speakerdeck.com/mkheck/powering-the-push-to-production["Powering the Push to Production: A multi-path, live action adventure!" presentation]

== Additional resources

https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools[VS Code plugin for ARM templates: Azure Resource Manager (ARM) Tools]

https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-bicep[VS Code plugin for syntax checking: Bicep for Visual Studio]

https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/[azd cli: Azure Developer CLI]

https://learn.microsoft.com/en-us/cli/azure/[az cli: Azure CLI]

https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform[VS Code plugin for Terraform files]
